language: java

os: linux
dist: bionic
script: mvn clean test

stages:
  - name: test
  - name: package
    if: branch = master

jobs:
  include:
    - stage: test
      name: "Test against OracleJDK 8 @ Ubuntu Trusty (14.04)"
      jdk: oraclejdk8
      dist: trusty

    - stage: test
      name: "Test against OracleJDK 11 @ Ubuntu Bionic (18.04)"
      jdk: oraclejdk11
      dist: bionic

    - stage: test
      name: "Test against OpenJDK 8 @ Ubuntu Bionic (18.04)"
      jdk: openjdk8
      dist: bionic

    - stage: test
      name: "Test against OpenJDK 11 @ Ubuntu Bionic (18.04)"
      jdk: openjdk11
      dist: bionic

    - stage: package
      name: "Packaging JARs"
      jdk: openjdk11
      script: mvn clean package -Dmaven.javadoc.skip=true

notifications:
  email:
    if: branch = master
    recipients:
      - juraj.somorovsky@hackmanit.de

