# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dtls

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_995ed56f77f64bce915e6ce01a0554f0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b2b8d7cd6c544029a5331130764e876a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_995ed56f77f64bce915e6ce01a0554f0 }}/dockerfile-openss:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dtls'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_141679aee9584f5d8831fb39f2fa02d0 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_995ed56f77f64bce915e6ce01a0554f0 }}/dockerfile-openss:${{ github.sha }}'